org: 77777
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /hello
          method: get
